# Generated by Django 6.0.6 on 2026-07-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('es_final', models.BooleanField(default=False, help_text='Marca estados que cierran el proceso')),
            ],
            options={
                'verbose_name': 'Estado de proceso',
                'verbose_name_plural': 'Estados de proceso',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('JUZGADO', 'Juzgado'), ('SALA', 'Sala'), ('TRIBUNAL', 'Tribunal'), ('OTRO', 'Otro')], default='JUZGADO', max_length=10)),
            ],
            options={
                'verbose_name': 'Juzgado',
                'verbose_name_plural': 'Juzgados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona natural'), ('JURIDICA', 'Persona juridica')], default='NATURAL', max_length=10)),
                ('nro_documento', models.CharField(blank=True, help_text='CI o NIT, si se conoce', max_length=50)),
            ],
            options={
                'verbose_name': 'Parte procesal',
                'verbose_name_plural': 'Partes procesales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_proceso', to='catalogos.categoria')),
            ],
            options={
                'verbose_name': 'Tipo de proceso',
                'verbose_name_plural': 'Tipos de proceso',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
    ]
