# Generated by Django 6.0.6 on 2026-07-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_remove_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte',
            name='nro_documento',
        ),
    ]
