# Generated by Django 6.0.6 on 2026-07-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador jurídico'), ('ABOGADO', 'Abogado')], default='ABOGADO', max_length=10),
        ),
    ]
