# Generated by Django 6.0.6 on 2026-07-07 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_correlativo', models.CharField(help_text='Correlativo dentro de su categoria, tal como en el Excel (Nº)', max_length=20)),
                ('nurej', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('abogado_referencia', models.CharField(blank=True, help_text='Nombre del profesional a cargo según el registro original (Excel), por si aún no tiene una cuenta de usuario creada en el sistema.', max_length=255)),
                ('fecha_registro', models.DateField(blank=True, help_text='Fecha de la demanda/acción, si se conoce', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('abogado_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_asignados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='catalogos.categoria')),
                ('estado_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='catalogos.estadoproceso')),
                ('juzgado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='catalogos.juzgado')),
                ('tipo_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='catalogos.tipoproceso')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleContrato',
            fields=[
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle_contrato', serialize=False, to='procesos.proceso')),
                ('proyecto', models.CharField(blank=True, max_length=500)),
                ('nro_contrato', models.CharField(blank=True, max_length=100)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('motivo_demanda', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Detalle de contrato',
                'verbose_name_plural': 'Detalles de contrato',
            },
        ),
        migrations.CreateModel(
            name='AccionFutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_futuras', to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Acción futura',
                'verbose_name_plural': 'Acciones futuras',
                'ordering': ['completada', 'fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='procesos/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='procesos.proceso')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento del proceso',
                'verbose_name_plural': 'Documentos del proceso',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateField(blank=True, help_text='Fecha del memorial/actuación, si se conoce', null=True)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.estadoproceso')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.estadoproceso')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='procesos.proceso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ACTIVA', 'Activa'), ('PASIVA', 'Pasiva')], max_length=10)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos', to='catalogos.parte')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='procesos.proceso')),
            ],
            options={
                'verbose_name': 'Parte del proceso',
                'verbose_name_plural': 'Partes del proceso',
            },
        ),
        migrations.AddIndex(
            model_name='proceso',
            index=models.Index(fields=['categoria', 'estado_actual'], name='procesos_pr_categor_efd9d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procesoparte',
            unique_together={('proceso', 'parte', 'rol')},
        ),
    ]
