# Generated by Django 6.0.6 on 2026-07-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='abogado_referencia',
        ),
    ]
